#initialisation PIN
LED_EMOTION_PIN = 18

BUTTON_SAVE_PIN = 16

BUTTON_POWER_ON_PIN = 11
BUTTON_POWER_OFF_PIN = 13

BUTTON_BLUETOOTH_ON_PIN = 15
BUTTON_BLUETOOTH_OFF_PIN = 29

GPIO_MODE = "BCM"
PIN_MAP = {
    "LED_EMOTION"      : LED_EMOTION_PIN,
    "BTN_SAVE"         : BUTTON_SAVE_PIN,
    "BTN_POWER_ON"     : BUTTON_POWER_ON_PIN,
    "BTN_POWER_OFF"    : BUTTON_POWER_OFF_PIN,
    "BTN_BT_ON"        : BUTTON_BLUETOOTH_ON_PIN,
    "BTN_BT_OFF"       : BUTTON_BLUETOOTH_OFF_PIN,
}

#caméra
CAMERA_INDEX = 0
SAVE_DIR = "/media/pi/NOM_DE_TA_SD/captures" #A MODIFIER AVEC L'ADRESSE DE LA CARTE SD
SAVE_CAPTURE_DIR = "/media/pi/NOM_DE_TA_SD/saved/captures" #A MODIFIER AVEC L'ADRESSE DE LA CARTE SD
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FRAMERATE = 9

#ventilateur
FAN_TEMP_LOW = 50
FAN_TEMP_HIGH = 70

#HAT
HAT_I2C_BUS = 1
HAT_I2C_ADDRESS = 0x3C

#LED 
LED_COUNT = 1          
LED_FREQ_HZ = 800000
LED_DMA = 10
LED_BRIGHTNESS = 255
LED_INVERT = False